language: node_js
node_js:
  - '0.10'
addons:
  sauce_connect: true
before_script:
  - 'gem update --system'
  - 'gem install compass'
  - 'cd angular'
  - 'npm install -g bower grunt-cli'
  - 'npm install'
  - 'bower install'
  - 'grunt test'
